### ISSUE TITLE
YTPlayer never gets ready()

### ISSUE THREAD

**Issue by thiagocoelho** [hpx7/meteor-youtube-iframe-player#1]
I don't know if I'm missing something here but my player instance never gets the ready state.

Here is what I'm doing right now:

``` javascript
var generalPlayer;
var YOUTUBE_READY = false;

Template.AppProducts.rendered = function() {
  generalPlayer = new YTPlayer('video-container', Template.AppProducts_video, {rel: 0, playsinline: 1});

  console.log(generalPlayer.ready());

  initialize_player();
}

function initialize_player() {
  console.log('initialize_player');
  if (!generalPlayer.ready()) return Meteor.setTimeout(function() {
    console.log(generalPlayer.ready());
    initialize_player();
  }, 50);

  YOUTUBE_READY = true;

  console.log('you can put a video to play now!');
}
```

**Comment by hpx7** [comment]
The ready() function is reactive, so you want to be checking it inside an Tracker autorun.

Instead of calling initialize_player() inside the rendered callback, try calling it inside an autorun.

**Comment by aramix** [comment]
I get an error like this when trying to play a video on my localhost
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:3000').
Why is this hapenning?

**Comment by hpx7** [comment]
@thiagocoelho could you try the newest version of this package? There is now a simpler API (check the README) and there have been some bug fixes.

**Comment by hpx7** [comment]
Assuming this is fixed.
