### ISSUE TITLE
Origin mismatch error

### ISSUE THREAD

**Issue by aramix** [hpx7/meteor-youtube-iframe-player#2]
@hpx7, I get an error like this when trying to play a video on my localhost
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:3000').
Why is this hapenning?

**Comment by hpx7** [comment]
Could you try again with the latest release?

**Comment by aramix** [comment]
seems to be fixed

**Comment by parthP7493** [comment]
Same issue i got and i m using custom jquery youtube player. When i run this jquery and html plugin its working fine. but when i convert that plugin into meteor its give me error like "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:3000')".thats why i cant play video in that player.
If anybody have some solution then provide me urgent i needed solution
