### ISSUE TITLE
Not working when player is not there when window.onYouTubeIframeAPIReady is called

### ISSUE THREAD

**Issue by mathieudutour** [hpx7/meteor-youtube-iframe-player#3]
Let's imagine that the player is not in the web page all the time.

Because the $.getScript('//www.youtube.com/iframe_api'); is called at the startup of Meteor, window.onYouTubeIframeAPIReady will potentially fire before the player is there and so, even if the YouTubeIframeAPI is ready, the player will never be.

Because i was in a hurry (HackLondon yeah!), i just put this : 

``` javascript
$(document).ready(function () {
    var a = document.createElement('script');
    a.id = 'www-widgetapi-script';
    a.src = 'https:' + '//s.ytimg.com/yts/jsbin/www-widgetapi-vfldTtH0_/www-widgetapi.js';
    $("head").append(a);
  });
```

before creating the YTPlayer but a cleaner thing to do would be to call $.getScript('//www.youtube.com/iframe_api'); when the template is created or something.

**Comment by hpx7** [comment]
Thanks for pointing this out. I made some changes that should fix this - try upgrading to the latest version.
