### ISSUE TITLE
object never gets ready

### ISSUE THREAD

**Issue by lgandecki** [hpx7/meteor-youtube-iframe-player#4]
I'm not sure how is this supposed to work..

Running something like this in the console:

var _ytPlayer = new YTPlayer("video", {height: '390',
    width: '640',
    videoId: 'M7lc1UVf-VE'})

and _ytPlayer.ready() always returns false.

Any hints?

It would be great if you could have simple examples of your code, at this point it's very hard to say whether the programmer is making an error, or is it the plugin that just doesn't work. I've spend a couple hours on this, doing TDD development using this module, just to realize that this is not working as expected.. 

Thanks for your work, hopefully we can get this to work. :) I'm starting to dig on my own.. Just wanted to let you know, that there might be a problem..

**Comment by lgandecki** [comment]
Looks like playerTemplate.rendered = function() never fires up. Even if I add {{> YTPlayer }} to the template, and then I can locate <div id="ytplayer"></div> in the DOM. 

I hacked it for now, so it works with only one yt video.

**Comment by hpx7** [comment]
You need to have `{{> YTPlayer name="video"}}` (getting `"video"` from your first comment) in your template. Let me know if this fixes it.

**Comment by hpx7** [comment]
@lgandecki have you gotten a chance to try out the above suggestion?
